CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  role ENUM('Expert', 'SubAdmin', 'SuperAdmin') NOT NULL DEFAULT 'Expert',
  city VARCHAR(120) NOT NULL DEFAULT 'DOUALA',
  active TINYINT(1) NOT NULL DEFAULT 1,
  data_scope ENUM('own', 'all') NOT NULL DEFAULT 'own',
  manage_users TINYINT(1) NOT NULL DEFAULT 0,
  panes_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY users_username_unique (username)
);

CREATE TABLE IF NOT EXISTS followups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  server_uid VARCHAR(80) NOT NULL,
  legacy_id VARCHAR(80) NULL,
  fingerprint CHAR(40) NOT NULL,
  event_timestamp VARCHAR(40) NOT NULL,
  expert VARCHAR(255) NOT NULL,
  school_name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255) NOT NULL DEFAULT '',
  contact_phone VARCHAR(80) NOT NULL DEFAULT '',
  followup_type VARCHAR(50) NOT NULL,
  notes TEXT NULL,
  outcome TEXT NULL,
  next_action TEXT NULL,
  next_date VARCHAR(40) NULL,
  cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(120) NOT NULL DEFAULT 'En cours',
  city VARCHAR(120) NOT NULL DEFAULT '',
  sector VARCHAR(255) NOT NULL DEFAULT '',
  school_type VARCHAR(120) NOT NULL DEFAULT '',
  category VARCHAR(120) NOT NULL DEFAULT '',
  effectif VARCHAR(80) NOT NULL DEFAULT '',
  location TEXT NULL,
  contact_role VARCHAR(120) NOT NULL DEFAULT '',
  source VARCHAR(120) NOT NULL DEFAULT 'nateiva-sale-analytic-api',
  created_by_username VARCHAR(120) NOT NULL DEFAULT '',
  device_id VARCHAR(120) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY followups_server_uid_unique (server_uid),
  UNIQUE KEY followups_fingerprint_unique (fingerprint),
  KEY followups_legacy_id_idx (legacy_id),
  KEY followups_expert_idx (expert),
  KEY followups_school_idx (school_name)
);

CREATE TABLE IF NOT EXISTS sync_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(120) NOT NULL,
  device_id VARCHAR(120) NOT NULL DEFAULT '',
  sync_type VARCHAR(80) NOT NULL,
  payload_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY sync_events_username_idx (username)
);
